services:
#    panel.example:
#        class: PanelBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    panel.user:
        class: PanelBundle\Service\UserServices
        arguments: ['@service_container']
        public: true