<?php

namespace ApiBundle\Repository;

/**
 * modsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modsRepository extends \Doctrine\ORM\EntityRepository
{
}
