<?php

namespace ApiBundle\Repository;

/**
 * ModUserRollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserRollRepository extends \Doctrine\ORM\EntityRepository
{
}
