<?php

namespace ApiBundle\Repository;

/**
 * modUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ModUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUser($username){
        $dql = "SELECT u FROM ApiBundle:ModUser u WHERE u.username = :username";
        return $this -> getEntityManager()
                     -> createQuery($dql)
                     -> setParameter('username',$username)
                     -> getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    public function getUserList($param){
        $dql = "SELECT u.id, u.nameSurname, u.email, u.status, u.username FROM ApiBundle:ModUser u ";
        if($param['query'] !=null){
            $dql = $dql." WHERE u.".$param['qtype']." ='".$param['query']."'";
        }
        $dql = $dql. "ORDER BY  u.".$param['sortname']." ".$param['sortorder'];
        return $this -> getEntityManager()
            -> createQuery($dql)
            -> setMaxResults($param['rp'])
            -> setFirstResult($param['offset'])
            -> getResult();
    }

}
