<?php

namespace ApiBundle\Repository;

/**
 * ModUserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroup(){
        $dql = "SELECT u.id, u.name FROM ApiBundle:ModUserGroup u";
        return $this -> getEntityManager()
            -> createQuery($dql)
            -> getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
