<?php

namespace PanelBundle\Repository;

/**
 * modUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUser($username){
        $dql = "SELECT u FROM PanelBundle:ModUser u WHERE u.username = :username";
        return $this -> getEntityManager()
                     -> createQuery($dql)
                     -> setParameter('username',$username)
                     -> getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
