<?php

namespace PanelBundle\Repository;

/**
 * ModUserAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserAuthRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserAuth($groupId){
        $dql = 'SELECT mua FROM PanelBundle:ModUserAuth mua WHERE mua.groupId = :group_id';
        return  $this -> getEntityManager()
                      -> createQuery($dql)
                      -> setParameter('group_id',$groupId)
                      -> getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
