<?php

namespace PanelBundle\Repository;

/**
 * ModUserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
